# Generated by Django 3.2.6 on 2021-08-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Free_Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Name')),
                ('Address', models.CharField(max_length=50, verbose_name='Address')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Contact', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Date', models.DateField()),
                ('Details', models.CharField(max_length=100)),
                ('File', models.FileField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Sign_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastName', models.CharField(max_length=50, verbose_name='LastName')),
                ('FirstName', models.CharField(max_length=50, verbose_name='FirstName')),
                ('MiddleName', models.CharField(max_length=50, verbose_name='MiddleName')),
                ('UserName', models.CharField(max_length=50, verbose_name='UserName')),
                ('Password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
    ]
