# Generated by Django 3.2.6 on 2021-08-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AoeApp', '0002_auto_20210809_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_quotation',
            name='Contact',
            field=models.IntegerField(),
        ),
    ]
