# Generated by Django 3.2.6 on 2021-08-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AoeApp', '0003_alter_free_quotation_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_quotation',
            name='Contact',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
    ]
