# Generated by Django 3.2.6 on 2021-08-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AoeApp', '0004_alter_free_quotation_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_quotation',
            name='Date',
            field=models.DateField(default=''),
        ),
    ]
