# Generated by Django 3.2.6 on 2021-08-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AoeApp', '0005_alter_free_quotation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='free_quotation',
            name='status',
            field=models.TextField(choices=[('Accept', 'Accept'), ('Deny', 'Deny'), ('Pending', 'Pending')], default='pending', max_length=20, null=True, verbose_name='status'),
        ),
    ]
